# Google App Engine configuration file
runtime: python39

env_variables:
  FLASK_SECRET_KEY: "REPLACE_WITH_YOUR_SECRET_KEY"
  GCP_PROJECT_ID: "REPLACE_WITH_YOUR_PROJECT_ID"
  FLASK_ENV: "production"

automatic_scaling:
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
